Added Introductory Problems Directory
anushreeBera/cses-fi pull request #1
Opened 2020-10-01 11:14 UTC by Zeo-shark

2020-10-01 16:43 UTC, anushreeBera commented
Please update coding convention

2020-10-01 17:05 UTC, Zeo-shark commented
> Please update coding convention

Updated code abiding coding conventions

2020-10-02 05:53 UTC, anushreeBera requested changes

2020-10-02 05:53 UTC, anushreeBera commented on Introductory Problems/ZeoShark_Weird_Algorithm1.java
> +        while(n!=1)
Please give appropriate spacing between operators and operand: while(n != 1)

2020-10-02 05:53 UTC, anushreeBera commented on Introductory Problems/Zeoshark_BitStrings.java
> +        Scanner in= new Scanner(System.in);
Spacing on either hands of assignment operator is uneven.

2020-10-02 07:06 UTC, Zeo-shark commented on Introductory Problems/ZeoShark_Weird_Algorithm1.java
> +        while(n!=1)
add appropriate spacing between operator and operands

2020-10-02 07:07 UTC, Zeo-shark commented on Introductory Problems/Zeoshark_BitStrings.java
> +        Scanner in= new Scanner(System.in);
add spacing in either side of the operator

2020-10-02 07:18 UTC, Zeo-shark commented on Introductory Problems/WeirdAlgorithm1.java
> +        }
**Learn to add inline comments + drag**

2020-10-02 08:07 UTC, merged